[build]
  command = "npm run docs:build"
  publish = "docs/.vitepress/dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Role = "authenticated"}

[[headers]]
  for = "/*"
  [headers.values]
    Basic-Auth = "yourUsername:yourPassword"