[build]
  command = "npm run docs:build"
  publish = "docs/.vitepress/dist"

[[edge_functions]]
  path = "/*"
  function = "auth"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"